In [1]:
import numpy as np
import pandas as pd
import re

data = pd.read_csv('trump.xlsm - trump.csv')

In [2]:
data.head()

,source,text,created_at,retweet_count,is_retweet,id_str,"Sentiment - (1 for pos, -1 for neg)"
0,Twitter for iPhone,"On Trade, France makes excellent wine, but so ...",11/13/18 13:07,28933,False,1.060000e+18,-1
1,Twitter for iPhone,Emmanuel Macron suggests building its own army...,11/13/18 11:50,36795,False,1.060000e+18,-1
2,Twitter for iPhone,.....of money spent on protecting other countr...,11/12/18 12:21,22140,False,1.060000e+18,-1
3,Twitter for iPhone,".....hundreds of billions of dollars, for the ...",11/12/18 12:10,18339,False,1.060000e+18,-1
4,Twitter for iPhone,Just returned from France where much was accom...,11/12/18 12:03,24546,False,1.060000e+18,-1

In [14]:
def clean_tweet(df):
    cleaned = df.text.replace('#', '') # Remove all '#' from the text
    cleaned = re.sub('http\S+', '', cleaned) # Remove all URLs from the text
    cleaned = re.sub('@\S+', '', cleaned) # Remove all @xxxx's from the text
    return cleaned

In [15]:
cleaned_text = data.apply(clean_tweet, axis=1)

In [19]:
data['text_cleaned'] = cleaned_text
data.head()

,source,text,created_at,retweet_count,is_retweet,id_str,"Sentiment - (1 for pos, -1 for neg)",text_cleaned
0,Twitter for iPhone,"On Trade, France makes excellent wine, but so ...",11/13/18 13:07,28933,False,1.060000e+18,-1,"On Trade, France makes excellent wine, but so ..."
1,Twitter for iPhone,Emmanuel Macron suggests building its own army...,11/13/18 11:50,36795,False,1.060000e+18,-1,Emmanuel Macron suggests building its own army...
2,Twitter for iPhone,.....of money spent on protecting other countr...,11/12/18 12:21,22140,False,1.060000e+18,-1,.....of money spent on protecting other countr...
3,Twitter for iPhone,".....hundreds of billions of dollars, for the ...",11/12/18 12:10,18339,False,1.060000e+18,-1,".....hundreds of billions of dollars, for the ..."
4,Twitter for iPhone,Just returned from France where much was accom...,11/12/18 12:03,24546,False,1.060000e+18,-1,Just returned from France where much was accom...

In [21]:
data.to_csv('Trump Tweets Cleaned.csv', index=False)